type User {
  id: ID!
  email: String!
  displayName: String!
  roles: [String!]!
  scopes: [String!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AuthPayload {
  accessToken: String!
  user: User!
}

input SignUpInput {
  email: String!
  password: String!
  displayName: String!
}

input SignInInput {
  email: String!
  password: String!
}

extend type Query {
  me: User
}

extend type Mutation {
  signUp(input: SignUpInput!): AuthPayload!
  signIn(input: SignInInput!): AuthPayload!
}