scalar DateTime

scalar JSON

type User {
  id: ID!
  email: String!
  displayName: String!
  roles: [String!]!
  scopes: [String!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AuthPayload {
  accessToken: String!
  user: User!
}

type SignOutPayload {
  success: Boolean!
}

type SignUpPayload {
  success: Boolean!
  user: User!
}

type CorrectionSession {
  id: ID!
  documentId: ID!
  documentType: String!
  status: String!
  version: Int!
  draftPayload: JSON!
  lockedBy: User!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input SignUpInput {
  email: String!
  password: String!
  displayName: String!
}

input SignInInput {
  email: String!
  password: String!
}

type Query {
  correctionSession(sessionId: ID!): CorrectionSession!
  correctionSessions: [CorrectionSession!]!
  me: User
}

type Mutation {
  signIn(input: SignInInput!): AuthPayload!
  signOut: SignOutPayload!
  signUp(input: SignUpInput!): SignUpPayload!
}