export const CORRECTION_EVENTS_QUEUE = 'correction.completed';

export const CORRECTION_OUTBOX_RELAY_SERVICE = 'CORRECTION_OUTBOX_RELAY_SERVICE';
export const CORRECTION_PUBLISHER_SERVICE = 'CORRECTION_PUBLISHER_SERVICE';
