export const MAX_PLATFORM_RESPONSE_BYTES = 256 * 1024;
export const MAX_PLATFORM_REQUEST_TIMEOUT_MS = 30_000;

export const PLATFORM_INVALID_RESPONSE = 'PLATFORM_INVALID_RESPONSE';
export const PLATFORM_REQUEST_FAILED = 'PLATFORM_REQUEST_FAILED';
export const PLATFORM_UNAVAILABLE = 'PLATFORM_UNAVAILABLE';

export const REQUEST_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
